"use client";
import { useState } from "react";
import { saveStaff, type StaffRecord } from "@/lib/data/client";

export function StaffForm({ staff, onClose, onSaved }: { staff?: StaffRecord; onClose: () => void; onSaved: () => Promise<void> }) {
  const [employeeId,setEmployeeId]=useState(staff?.employee_id||""); const [name,setName]=useState(staff?.full_name||""); const [department,setDepartment]=useState(staff?.department||""); const [position,setPosition]=useState(staff?.position||""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");try{await saveStaff({id:staff?.id,employee_id:employeeId,full_name:name,department,position});await onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Could not save staff member.");setSaving(false)}}
  return <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-dismiss" onClick={onClose} aria-label="Close"/><section className="drawer"><div className="drawer-header"><div><p className="eyebrow">Staff directory</p><h2>{staff?"Edit staff member":"Add staff member"}</h2><p>Directory details are used across every appraisal cycle.</p></div><button className="icon-button" onClick={onClose}>×</button></div><form className="form-stack form-offset" onSubmit={submit}><label>Employee ID<input required value={employeeId} onChange={e=>setEmployeeId(e.target.value)} placeholder="EMP007"/></label><label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Alex Morgan"/></label><label>Department<input value={department} onChange={e=>setDepartment(e.target.value)} placeholder="Operations"/></label><label>Position<input value={position} onChange={e=>setPosition(e.target.value)} placeholder="Team Lead"/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="button button-secondary" onClick={onClose}>Cancel</button><button className="button" disabled={saving}>{saving?"Saving…":"Save staff"}</button></div></form></section></div>
}
