"use client";
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import '../login/login.css';
export default function ResetPasswordPage(){
  const [ready,setReady]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
  useEffect(()=>{createClient().auth.getUser().then(({data,error})=>setReady(!error&&!!data.user)).catch(()=>setReady(false)).finally(()=>setChecking(false));},[]);
  async function save(event:React.FormEvent){event.preventDefault();setError('');if(password!==confirm){setError('The passwords do not match.');return;}setBusy(true);try{const auth=createClient().auth;const {error}=await auth.updateUser({password});if(error){setError('Could not change the password. Request a new reset link or try a different password.');return;}setPassword('');setConfirm('');const result=await auth.signOut();if(result.error){setError('Password updated, but sign-out could not be completed. Go to the sign-in page to manage your session.');setReady(false);return;}setDone(true);}catch{setError('Connection failed. Please try again.');}finally{setBusy(false);}}
  return <main className="login-screen login-standalone"><section className="login-panel"><div className="login-card"><p className="login-eyebrow">PMS Executive Suite</p><h2>Choose a new password</h2>{checking?<p role="status">Verifying your session…</p>:done?<p role="status" className="login-message">Your password has been updated. Sign in again with your new password.</p>:!ready?<p className="login-notice">Open a valid password-reset email in this browser before setting your password.</p>:<form onSubmit={save} className="login-form"><label>New password<input type="password" autoComplete="new-password" minLength={12} required value={password} disabled={busy} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm new password<input type="password" autoComplete="new-password" minLength={12} required value={confirm} disabled={busy} onChange={e=>setConfirm(e.target.value)}/></label><small>Use at least 12 characters.</small><button className="login-primary" disabled={busy}>{busy?'Updating…':'Update password'}</button></form>}{error&&<p role="alert" className="login-error">{error}</p>}<Link className="login-text" href="/login">Back to sign in</Link></div></section></main>;
}
